/**
    Copyright (C) 2014  www.cybersearch2.com.au

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/> */
package au.com.cybersearch2.classy_logic.jpa;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * City
 * @author Andrew Bowley
 * 8 Feb 2015
 */
@Entity(name="City")
public class City 
{

	/**
     * City default constructor for ormlite
	 */
	public City() 
	{
	}

	/** We use this field-name so we can query for posts with a certain id */
	public final static String ID_FIELD_NAME = "id";

	/** This id is generated by the database and set on the object when it is passed to the create method */
    @Id @GeneratedValue
 	int id;

	@Column
	String name;
	
	@Column
	int altitude;

	/**
	 * Create City object
	 * @param name City name
	 * @param altitude Height in feet
	 */
	public City(String name, int altitude) 
	{
		this.name = name;
		this.altitude = altitude;
	}

	@Override
	public String toString() 
	{
		return "city(name = " + name + ", altitude = " + altitude +")";
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAltitude() {
		return altitude;
	}

	public void setAltitude(int altitude) {
		this.altitude = altitude;
	}
	
	
}
