BEGIN TRANSACTION;
INSERT INTO `User_Info` VALUES (1);
INSERT INTO `Issue` VALUES (1,'Start','The TV won''t turn on');
INSERT INTO `Issue` VALUES (2,'Video','There is no picture/video');
INSERT INTO `Issue` VALUES (3,'Remote','The remote control does not work');
INSERT INTO `Issue` VALUES (4,'Set top box','The cable/set top box remote control doesn''t turn the TV on or off, or adjust the volume');
INSERT INTO `Check` VALUES (1,'Power cord','Make sure the AC power cord is securely plugged in to the wall outlet');
INSERT INTO `Check` VALUES (2,'Wall outlet','Make sure the wall outlet is working');
INSERT INTO `Check` VALUES (3,'Remote','Try pressing the POWER button on the TV to make sure the problem is nto the remote.');
INSERT INTO `Check` VALUES (4,'Connections','Check cable connections (remove and reconnect all cables connected to the TV and external devices)');
INSERT INTO `Check` VALUES (5,'Cables','Set your external device''s (Cable/Set Box, DVD, Blu-ray etc) video outputs to match the connections to the TV input.For example, if an external device''s output is HDMI, it should be connected to an HDMI input on the TV.');
INSERT INTO `Check` VALUES (6,'Connected devices','Make sure your connected devices are powered on.');
INSERT INTO `Check` VALUES (7,'Source','Be sure to select the TV''s correct source by pressing the SOURCE button on the remote control.');
INSERT INTO `Check` VALUES (8,'Running state','Reboot the connected device by unplugging and then reconnecting the device''s power cable');
INSERT INTO `Check` VALUES (9,'Batteries','Replace the remote control batteries with the poles (+/-) in the right direction');
INSERT INTO `Check` VALUES (10,'Sensor','Clean the sensor''s transmission window on the remote');
INSERT INTO `Check` VALUES (11,'Pointing','Try pointing the remote directly at the TV from 5-6 feet away');
INSERT INTO `Check` VALUES (12,'Programme','Programme the Cable/Set remote control to operate the TV. Refer to the Cable/Set user manual for the SAMSUNG TV code');
INSERT INTO `Check` VALUES (13,'Support','Contact Support');
COMMIT;
