BEGIN TRANSACTION;
CREATE TABLE `User_Info` (`version` INTEGER );
CREATE TABLE `Issue` (`id` INTEGER PRIMARY KEY AUTOINCREMENT , `name` VARCHAR , `observation` VARCHAR );
CREATE TABLE `Check` (`id` INTEGER PRIMARY KEY AUTOINCREMENT , `name` VARCHAR , `instruction` VARCHAR );
COMMIT;
