/**
    Copyright (C) 2014  www.cybersearch2.com.au

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/> */
package au.com.cybersearch2.classy_logic.tutorial15;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Transient;

/**
 * Agri10Year
 * @author Andrew Bowley
 * 19 Mar 2015
 */
@Entity(name = "Agri10Year")
public class Agri10Year 
{
	
	public Agri10Year() 
	{
	}

	/** This id is generated by the application */
    @Id
 	int id;

    @OneToOne
    @JoinColumn(name="country_id", referencedColumnName="id")
	Country country;
    
    @Transient
    String countryName;
	
	@Column(nullable = false)
	Double surfaceArea;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
		countryName = country.getCountry();
	}

	public Double getSurfaceArea() {
		return surfaceArea;
	}

	public void setSurfaceArea(Double surfaceArea) {
		this.surfaceArea = surfaceArea;
	}

	/**
	 * @return the countryName
	 */
	public String getCountryName() 
	{
		return countryName;
	}

	/**
	 * @param countryName the countryName to set
	 */
	public void setCountryName(String countryName) 
	{
		this.countryName = countryName;
	}
	
	
}
